<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0JOHASU" failures="0" tests="5" name="com.testNG.RunTestNG" time="9.666" errors="1" timestamp="2022-10-07T17:17:11 COT" skipped="0">
  <testcase classname="com.testNG.RunTestNG" name="pruebaInicialTestNG" time="0.036"/>
  <system-out/>
  <testcase classname="com.testNG.RunTestNG" name="Registro" time="9.617">
    <error type="java.lang.InterruptedException">
      <![CDATA[java.lang.InterruptedException
at ClasesBase.ClaseBase.click(ClaseBase.java:148)
at PagesObjects.PageObjectRegistro.crearMiCuenta(PageObjectRegistro.java:28)
at com.testNG.RunTestNG.Registro(RunTestNG.java:147)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Registro -->
  <system-out/>
  <testcase classname="com.testNG.RunTestNG" name="alertas" time="0.001"/>
  <system-out/>
  <testcase classname="com.testNG.RunTestNG" name="Widgets" time="0.005"/>
  <system-out/>
  <testcase classname="com.testNG.RunTestNG" name="mercury" time="0.007"/>
  <system-out/>
</testsuite> <!-- com.testNG.RunTestNG -->
